### ISSUE TITLE
Doesn't work with React-Blessed 0.2

### ISSUE THREAD

**Issue by zautumnz** [dundalek/react-blessed-contrib#1]
React-Blessed 0.2.x updated to use React 16, and changed their dist/ directory structure (maybe should've been a semver major change on their part), which breaks this package.

**Comment by dundalek** [comment]
Thanks for the report, I missed the news. It is not just the directory structure, the internals changed significantly as well. I will have a look and will try to find a method to work with the new version.

**Comment by dundalek** [comment]
I just published a new version `v0.2.0` that works with latest react-blessed and React 16. Enjoy and please open a new issue if you find anything broken.

**Comment by zautumnz** [comment]
Thank you! 🎈 🎉
