### ISSUE TITLE
Docs should mention contrib widget ref is available on `myRef.widget`

### ISSUE THREAD

**Issue by philraj** [dundalek/react-blessed-contrib#4]
Took me some time to realize that the ref to the internal wrapped contrib widget is available on `myRef.widget`:
```
<Log ref={x => this.myRef = x} />

// ...

this.myRef.widget.scrollTo(...)
```
I'm glad it's available there, and I understand why it was done this way, but would be nice if the docs mentioned this.

**Comment by dundalek** [comment]
That sounds good. Could you add it to the readme and open a PR?

**Comment by philraj** [comment]
https://github.com/dundalek/react-blessed-contrib/pull/5 Here ya go.
