### ISSUE TITLE
Render in browser

### ISSUE THREAD

**Issue by mark-zarandi** [dundalek/react-blessed-contrib#7]
Great job with this library, very snappy.  Is there a way to render this in a browser?

**Comment by dundalek** [comment]
Hi, you would need to have blessed or neo-bleseed libraries working in browser. Some attempts that seemed to be made so far:
- https://github.com/chjj/blessed/issues/97
- https://github.com/embarklabs/neo-blessed/issues/17

**Comment by mark-zarandi** [comment]
Nice, thanks.
